Ik ms/#104 clone detector based on suffix tree
ACCULA/accula pull request #112
Opened 2020-07-17 14:07 UTC by VanyaKrylov

Closes #104

2020-07-17 17:59 UTC, lamtev requested changes
Посмотрел через GitHub. Замечания, в основном, стилевые.
Логику чуть позднее посмотрю в IDE

PS: при мердже обязательно "squash and merge" кнопкой надо воспользоваться
PSS: давай изменим название ПР, хотя бы убрав из него название ветки
PSSS: нужно в новых файлах пройтись реформаттером, чтобы импорты отсортировать в лексикографическом порядке

2020-07-17 17:59 UTC, lamtev commented on api/build.gradle.kts
> +    antlr("org.antlr:antlr4:4.8-1")
Я бы вынес в переменную версию. Удобнее будет потом в 1 месте менять

2020-07-17 17:59 UTC, lamtev commented on api/build.gradle.kts
> +    implementation(fileTree("dir" to "libs", "include" to  "*.jar"))
будем артефакт тянуть из artifactory

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +import java.util.*;
Не используем такие импорты. Явно прописываем все использования

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +import static org.accula.api.detector.util.SuffixTreeUtils.*;
Не используем такие импорты. Явно прописываем все использования

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +
Лишняя пустая строка

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +public class SuffixTreeCloneDetector implements CloneDetector {
`final`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static final CloneIndexer CLONE_DETECTOR_INSTANCE = CloneIndexer.INSTANCE;
@vaddya однажды предложил для таких случаев, когда класс не контейнер с данными, а еще и обладает бизнес-логикой, именовать его как обычное поле camel case'ом c маленькой буквы. Например, так именуют `log`. Мне данное предложение понравилось. И теперь мы придерживаемся такой конвенции

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +     * Creates an instance of the class with the specified minimal clone length
Избыточный `javadoc`, совершенно понятно и без него что зачем

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +public class SuffixTreeCloneDetector implements CloneDetector {
Не хватает `@author` `javadoc`, который мы договорились указывать для всех классов

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    public SuffixTreeCloneDetector(final int minCloneLength) {
Раз уж используем `lombok`, то давай и здесь сделаем `@RequiredArgsConstructor`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                                                             final Flux<FileEntity> sourceFiles) {
Обычно переносим, когда не влезает на экран (до 140 символов)

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private List<Tuple2<CodeSnippet, CodeSnippet>> clones(@NonNull final List<FileEntity> targetFiles,
`@lombok.NonNull` генерирует код с проверкой на `null`. Мы их не используем.
Более того, `zipWith(Publisher, BiFunction)` не может подставить `null`, так что в любом случае проверка избыточна

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                                                          @NonNull final List<FileEntity> sourceFiles) {
Тоже влезаем на экран, не переносим

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private void extractClonesIntoMapForSourceMethod(@NonNull final Long methodId,
Не используем `@NonNull` (см. выше)

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                                                             List<CodeSnippet>> cloneClassCodeSnippetsMap) {
Странный перевод строки. Я сначала прочитал это как 3-й аргумент метода

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                                                                            List<CodeSnippet>> cloneClassCodeSnippetsMap) {
Видимо так специально сделано было, раз уже 2-й раз встречается. На мой взгляд, только сбивает с толку. @vaddya ?

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                .max(Long::compareTo).orElseThrow();
Не нашел места, где эксепшен хэндлится

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    public void addClonesToListForTargetMethod(@NonNull final Long methodId,
Не используем `@NonNull` (см. выше)

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private Optional<TreeCloneClass> getTreeCloneClassForMethod(@NonNull final Long methodId) {
Не используем `@NonNull` (см. выше)

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void putCodeSnippetIntoCloneClassCodeSnippetsMap(@NonNull final CodeSnippet codeSnippetValue,
Не используем `@NonNull` (см. выше)

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void getClonesForCloneClassIntoList(@NonNull final CodeSnippet codeSnippetTarget,
Не используем `@NonNull` (см. выше)

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static long addFilesIntoTree(@NonNull final List<FileEntity> files,
Не используем `@NonNull` (см. выше)

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static long addFileIntoTree(@NonNull final FileEntity file,
Не используем `@NonNull` (см. выше)

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                .orElseThrow();
Здесь `orElseThrow()` на новой строке. В некоторых местах на одной строке с предыдущим оператором. Предлагаю привести к единому стилю

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/JavaListener.java
> +    public void enterMethodBody(Java9Parser.MethodBodyContext ctx) {
`final Java9Parser.MethodBodyContext ctx`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/JavaListener.java
> +public class JavaListener extends Java9BaseListener {
`final`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Parser.java
> +
лишняя пустая строка

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Parser.java
> +    private Parser() {}
Так сложилось, что в остальных местах в пустых методах закрывающий брейс переведен на новую строку. Предлагаю и здесь сделать так же

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Parser.java
> +        if (TokenFilter.primitiveTypes.contains(token.getType()))
Нужно добавить braces

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Token.java
> +        return Objects.hash(type);
Выглядит как плохая хэш-функция. Как я вижу, `Token` еще и в HashSet (считай HashMap) используется.
И, наверное, `Java9Lexer.Identifier` константная штука, и у всех токенов будет один хэш.
Нужно либо разъяснение ситуации, либо надо переписать хэш-функцию нормально

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Token.java
> +@Getter
Предлагаю так:
`@Data` сделает `@Getter ` для всех филдов, `@Setter` - для не `final` филдов. Также будет `@EqualsAndHashCode`. Если нужно сравнение и `hashCode` только по части филдов, то можно сделать так: `@EqualsAndHashCode(onlyExplicitlyIncluded = true)` и накинуть `@EqualsAndHashCode.Include` на те поля, которые нужно включить в `equals` и `hashCode`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Token.java
> +        return type.equals(token.type);
± то же самое, что и с `hashCode`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Token.java
> +        return Comparator
Не усложнение? =) 
```java
return type - o.type
```

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/TokenFilter.java
> +public class TokenFilter {
`final`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/TokenFilter.java
> +public class TokenFilter {
private ctor

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/TokenFilter.java
> +public class TokenFilter {
раз хватает у филдов `package-private`, значит и у класса должно хватить

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/TokenFilter.java
> +    static final Set<Integer> excludeTokens = Set.of(
Не по конвенции. `EXCLUDE_TOKENS` ?

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/TokenFilter.java
> +    static final Set<Integer> primitiveTypes = Set.of(
см. выше

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +
лишняя пустая строка

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +    public static CodeSnippet getCodeSnippetFromEdge(@NonNull final Edge edge, final int cloneLength) {
Где-то наверху объяснил, что не используем `@lombok.NonNull`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +    private SuffixTreeUtils() {}
В проекте принято переносить на другую строку закрывающий брейс

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        return new CodeSnippet((CommitSnapshot) begin.getCommitSnapshot(),
Почти наверняка такое форматирование поедет в IDE. Если хочется, чтобы так сохранилось, то нужно обернуть в:
```java
//@formatter:off
... <- perfectly formatted code here
//@formatter:on
```

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        int sequenceEndIndex = edge.getBegin();
`final`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        Token begin = (Token) edge.getSequence().get(sequenceEndIndex - cloneLength);
`final`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        Token end = (Token) edge.getSequence().get(sequenceEndIndex - 1);
`final`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +    public static Stream<Edge> edgesFromTreeCloneClassForMethod(@NonNull final TreeCloneClass treeCloneClass,
не используем `@lombok.NonNull`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +    public static boolean matchesToMethod(@NonNull final Edge edge, @NonNull final Long methodId) {
не используем `@lombok.NonNull`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +    public static Token extractBeginToken(@NonNull final TreeCloneClass treeCloneClass) {
не используем `@lombok.NonNull`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +    public static Token extractEndToken(@NonNull final TreeCloneClass treeCloneClass) {
не используем `@lombok.NonNull`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +    public static boolean matchesToMethod(@NonNull final Edge edge, @NonNull final Long methodId) {
Не эксперт, но думаю, что `to` - лишний. `matchesMethod` - вполне себе правильно, нет?

2020-07-17 17:59 UTC, lamtev commented on api/src/test/resources/testfiles/source/Code.java
> +package name;
Мы можем поменять расширение на НЕ `.java` ? Чтобы в IDE лишний раз в поисковую выдачу не попадало это все. И чтобы это не индексировалось, как java код тулзами. `*.testdata` (???)

2020-07-17 17:59 UTC, lamtev commented on api/src/test/resources/testfiles/source/Code.java
> +}
Даже GitHub красным подсвечивает =) И ниже

2020-07-17 17:59 UTC, lamtev commented on api/src/test/java/org/accula/api/detector/CloneDetectorTest.java
> +        var repoOwner       = new GithubUser(1L, "owner", "owner", "ava", false);
обычно не ревьюю тесты. ну тут такая же фигня с форматированием. Я бы завернул в коммент, как где-то выше предложил

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/JavaListener.java
> +    private final List<List<Token>> functions = new LinkedList<>();
Эммм, `LinkedList`? Ну попробуйте убедить, что здесь нужен именно он 😄

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                   final int cloneLength = treeCloneClass.getLength();
Всего 1 использование, можно заинлайнить

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                   var cloneClass = new CloneClass(extractBeginToken(treeCloneClass), extractEndToken(treeCloneClass));
`final`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                       var codeSnippetTarget = getCodeSnippetFromEdge(edge, cloneLength);
`final`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                .orElseThrow();
Не нашел места, где эксепшен хэндлится

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                    var cloneClass = new CloneClass(extractBeginToken(treeCloneClass), extractEndToken(treeCloneClass));
`final`

2020-07-17 17:59 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                        var codeSnippet = getCodeSnippetFromEdge(edge, cloneLength);
`final`

2020-07-17 18:06 UTC, vaddya commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static final CloneIndexer CLONE_DETECTOR_INSTANCE = CloneIndexer.INSTANCE;
Субъективно, конечно, но раз в остальной часте проекта такое правило ввели, стоит его придерживаться и здесь

2020-07-17 18:06 UTC, vaddya commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                                                                            List<CodeSnippet>> cloneClassCodeSnippetsMap) {
Согласен

2020-07-17 19:16 UTC, lamtev requested changes
Посмотрел в IDE, нашел еще кое-что
@MarkMarkyMarkus плз посмотри по своим файлам замечания

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        return (element instanceof EndToken endToken) && (endToken.getIdSequence() == methodId);
Из preview-фич договорились использовать пока только текстовые блоки (и то без нового API String).
Нужно здесь, и если еще есть где-то, заменить на java 14 stable API

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +package org.accula.api.detector.util;
Не хватает в пакете аннотированного `@NonNullApi` package-info

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        return treeCloneClass.getClones().iterator().next().getFirstElement();
`iterator().next()` вызывается без проверки `hasNext()`. И в месте вызова тоже не грантируется, что передается непустая коллекция. Уверен, что тут можно в итоге словить `NoSuchElementException`

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        return treeCloneClass.getClones().iterator().next().getLastElement();
см. выше `extractBeginToken`

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        final int lastElementIndex = edge.getSequence().size() - 1;
`getSequence()` точно имеет нулевую вычислительную сложность? Я когда-то давно смотрел код плагина, и есть ощущение, что эта фигня может вычисляться каждый раз. Лучше проверить

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        final var element = edge.getSequence().get(lastElementIndex);
небезопасный способ получения lastElement. Уверен, что последовательность не пуста?

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        final var element = edge.getSequence().get(lastElementIndex);
По аналогии с верхней переменной можно тоже `lastElement` назвать

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void putCodeSnippetIntoCloneClassCodeSnippetsMap(@NonNull final CodeSnippet codeSnippetValue,
суффиксы `value`, `key` точно нужны? вроде и без них все понятно

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void putCodeSnippetIntoCloneClassCodeSnippetsMap(@NonNull final CodeSnippet codeSnippetValue,
Не эксперт, но считаю, что в английском правильно так:
1. Code snippets
2. Code snippet list, code snippet map
То есть, `s` лишняя
В других местах то же самое

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void getClonesForCloneClassIntoList(@NonNull final CodeSnippet codeSnippetTarget,
Предложил бы возвращать лист, а не тащить из рута этот лист в качестве параметра

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    public void addClonesToListForTargetMethod(@NonNull final Long methodId,
`private`

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        int sequenceEndIndex = edge.getBegin();
как-то контр-интуитивно вышло, что `getBegin()` возвращает `endIndex`

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        Token begin = (Token) edge.getSequence().get(sequenceEndIndex - cloneLength);
Здесь и ниже нельзя выйти за границы?

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Parser.java
> +                        .map(Parser::anonymize)
Два `map` подряд можно схлопнуть

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Parser.java
> +        final var lexer = new Java9Lexer(CharStreams.fromString(file.getContent()));
Хочется убедиться в том, что `Java9Lexer` и `Java9Parser` не нужно переиспользовать или довольно "дёшево" постоянно пересоздавать

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Token.java
> +package org.accula.api.detector.parser;
Посмотрел в IDE. Кажется, данный класс не используется. Везде в когде фигурирует другой класс `Token` из плагина А. Сухинина.

ДА, удалил класс, все скомпилировалось без него. Либо он не нужен, либо в другом коде он ошибочно не используется

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/JavaListener.java
> +    public void enterClassOrInterfaceType(Java9Parser.ClassOrInterfaceTypeContext ctx) {
`final`

2020-07-17 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        return (element instanceof EndToken endToken) && (endToken.getIdSequence() == methodId);
Cравнение двух ссылок на `Long` . При выходе за закэшированный диапазон будет неправильно отрабатывать

2020-07-17 22:50 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +        final var suffixTree = CLONE_DETECTOR_INSTANCE.getTree();
Кажется, что это нерабочий вариант. Дерево - синглтон, а значит в него могут параллельно добавлять сиквенсы разные потоки. А еще один поток может вызвать `.clear()`, пока другому дерево еще нужно. Нужно отказаться от синглтона, и на каждый вызов этого метода создавать новый инстанс дерева. На данном этапе такого предложенного решения будет достаточно. А в будущем сделаем, как обсуждалось, 1 дерево на 1 проект

2020-07-20 17:07 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void putCodeSnippetIntoCloneClassCodeSnippetsMap(@NonNull final CodeSnippet codeSnippetValue,
`List` можно опустить, заменив на множественное число - CodeSnippet**s**, что я и сделал. Так лаконичнее и понятнее чем `cloneClassCodeSnippetListMap`.

2020-07-20 17:07 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void putCodeSnippetIntoCloneClassCodeSnippetsMap(@NonNull final CodeSnippet codeSnippetValue,
Для пущей наглядности

2020-07-20 17:07 UTC, VanyaKrylov commented on api/build.gradle.kts
> +    implementation(fileTree("dir" to "libs", "include" to  "*.jar"))
Пока не тянем

2020-07-20 17:07 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +     * Creates an instance of the class with the specified minimal clone length
Мне кажется не очевидным что под `минимальной длинной клона` подразумевается именно число токенов, а не число строк и т.д. - комментарий направлен на то, чтобы явно это указать

2020-07-20 17:07 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    public SuffixTreeCloneDetector(final int minCloneLength) {
Вынесен в явный конструктор ради комментария, см. выше

2020-07-20 17:07 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                                                             final Flux<FileEntity> sourceFiles) {
[Врёшь!](https://github.com/ACCULA/accula/blob/d843756c4e516c9acbeee3abcf1bdcab413908b8/api/src/main/java/org/accula/api/code/JGitCodeLoader.java#L190) Мне кажется так нагляднее

2020-07-20 17:07 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                                                          @NonNull final List<FileEntity> sourceFiles) {
Ориентируюсь на дэфолтный `hard wrap` в Intellij, равный 120

2020-07-20 17:07 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +        final var suffixTree = CLONE_DETECTOR_INSTANCE.getTree();
Согласен с замечанием, я исправлял это, но во время рефакторинга затёр видимо изменение - поправлю. Предложенный вариант не будет работать - сам `CloneIndexer` синглотонный и подсовывать ему новое дерево - не решит проблему. Но всё то же самое с `CloneIndexer` - сработает.

2020-07-20 17:07 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                   final int cloneLength = treeCloneClass.getLength();
Вынес для читаемости. Оставляю

2020-07-20 17:07 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void getClonesForCloneClassIntoList(@NonNull final CodeSnippet codeSnippetTarget,
В планах распараллелить этот фрагмент и обернуть во `Flux` (`addClonesToListForTargetMethod`), там же пересмотреть манипуляции с листом. Сейчас реализация потребует конкатенации листов, что может сказаться на временной сложности. Я бы пока оставил как есть

2020-07-20 17:07 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/parser/Token.java
> +package org.accula.api.detector.parser;
Это временное решение, в дальнейшем будет использоваться данный класс

2020-07-20 17:07 UTC, VanyaKrylov commented on api/build.gradle.kts
> +    antlr("org.antlr:antlr4:4.8-1")
Согласен

2020-07-20 17:12 UTC, lamtev commented on api/build.gradle.kts
> +    implementation(fileTree("dir" to "libs", "include" to  "*.jar"))
Тогда, может, `implementation(file("libs/suffix-tree-lib-name.jar"))` чтобы лишнее не тянулось. Вдруг там еще что-то лежит?

Хотя я все же надеюсь, что до влития этого ПР будет артифактори. Все-таки jar в git это бееее

2020-07-20 17:15 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        final int lastElementIndex = edge.getSequence().size() - 1;
Да нет, обычный геттер, для `var` в котлине

2020-07-20 17:17 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        return treeCloneClass.getClones().iterator().next().getFirstElement();
Нет

2020-07-20 17:17 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +     * Creates an instance of the class with the specified minimal clone length
Кажется, что люди, более менее разбирающиеся в данной предметной области, понимают о чем речь. А другие этот проект разрабатывать не будут.
И если не очевидно все равно, то не думал назвать параметр более говоряще? `cloneMinTokenCount` или более изящный вариант

2020-07-20 17:25 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                                                             final Flux<FileEntity> sourceFiles) {
<img width="1212" alt="Screenshot 2020-07-20 at 20 22 58" src="https://user-images.githubusercontent.com/10428179/87967186-24079200-cac7-11ea-9aee-ac80e6bf6203.png">

2020-07-20 17:30 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                                                          @NonNull final List<FileEntity> sourceFiles) {
Если сигнатура влезает в 140, то на горизонтальных экранах все вмещается и удобно смотреть. Когда уберешь, как раз будет влезать в 140. В общем, ладно

2020-07-20 17:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                   final int cloneLength = treeCloneClass.getLength();
`listSize` vs `list.size()` =)

2020-07-20 17:36 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void putCodeSnippetIntoCloneClassCodeSnippetsMap(@NonNull final CodeSnippet codeSnippetValue,
Проглядел, что там именно List от сниппетов. Согласен

2020-07-20 17:38 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void getClonesForCloneClassIntoList(@NonNull final CodeSnippet codeSnippetTarget,
распараллелить вставку элементов в массив?

2020-07-20 17:39 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Token.java
> +package org.accula.api.detector.parser;
Тогда много вопросов по нему. Они оставлены ниже

2020-07-20 17:43 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        final int lastElementIndex = edge.getSequence().size() - 1;
Видел всякие конструкции там типа:
```kotlin
var field: T
  get() = this.list.map { ... } .../* complicated operators*/ ... .map { ... }
```

Поэтому решил спросить

2020-07-20 17:46 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +        final var suffixTree = CLONE_DETECTOR_INSTANCE.getTree();
В чем проблема сделать CloneIndexer не синглтоном?

2020-07-20 18:40 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                   final int cloneLength = treeCloneClass.getLength();
А, не так понял сначала, думал речь о методе в целом, а не об одной переменной. My fault. С инлайнингом переменной согласен, поменяю

2020-07-20 19:20 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        return treeCloneClass.getClones().iterator().next().getLastElement();
Аналогично

2020-07-20 19:22 UTC, VanyaKrylov commented on api/build.gradle.kts
> +    implementation(fileTree("dir" to "libs", "include" to  "*.jar"))
Где наш jfrog artifactory? :)

2020-07-20 19:26 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +     * Creates an instance of the class with the specified minimal clone length
В целом согласен. Не смог придумать говорящее название для переменной, чтобы при этом основной смысл не затирался, потому что `cloneMinTokenCount` как то не так наглядно. Но наверное всё же удалю коммент, как оказалось (на твоём примере) очевидности он не довляет

2020-07-20 19:27 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    public SuffixTreeCloneDetector(final int minCloneLength) {
**upd** решено всё же следовать замечанию и добавить конструктор через `lombok`

2020-07-20 19:30 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    public SuffixTreeCloneDetector(final int minCloneLength) {
Огонь!

2020-07-20 19:30 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +     * Creates an instance of the class with the specified minimal clone length
> на твоем примере

Это типа я неправильно понял смысл?)

2020-07-20 19:31 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +     * Creates an instance of the class with the specified minimal clone length
Кстати, ничто не мешает добавить javadoc на field

2020-07-20 19:33 UTC, lamtev commented on api/build.gradle.kts
> +    implementation(fileTree("dir" to "libs", "include" to  "*.jar"))
Прямо сейчас попробую завести

2020-07-20 19:38 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +     * Creates an instance of the class with the specified minimal clone length
Это типо ты не понял зачем это :) Значит не показательно. Где то читал что JavaDoc на `private` поля автоматически не подхватывается при генерации документации и что лучше типо ставить на конструкторе. Но в целом действительно ничего не мешает

2020-07-20 19:41 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                                                             final Flux<FileEntity> sourceFiles) {
Ну ладно тогда. А почему именно 140? Мне с моим фонтом при открытой вкладке проектов дэфолтное значение Intellij 120 как раз оптимально

2020-07-20 22:48 UTC, lamtev commented on api/build.gradle.kts
> +    implementation(fileTree("dir" to "libs", "include" to  "*.jar"))
__/api/build.gradle.kts__:
```kotlin
    ...
    id("net.bytebuddy.byte-buddy-gradle-plugin") version "1.10.11"
}

repositories {
    maven(url = "https://dl.bintray.com/accula/clone-detector") // <---
}

...

dependencies {
    ...
    implementation("org.accula:clone-detector:1.0.0") // <---
    ...
}
...
```

2020-07-20 22:55 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                                                             final Flux<FileEntity> sourceFiles) {
Эмпирически подобранное, идеальное значение, учитывающее ситуацию с мониторами сегодня и, конечно, стиль кодинга, который получается с использованием всех этих функциональных операторов, а также порой длинных (в силу попытки улучшить ясность) названий классов, переменных, методов

Решили так: 
1) стремимся в боди методов умещаться в 120
2) в филдах и сигнатурах методов норм до 140
3) если в боди никак не влезть в 120, то верхняя граница - 140

2020-07-22 20:06 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +        final var suffixTree = CLONE_DETECTOR_INSTANCE.getTree();
Ни в чём, уже сделано

2020-07-22 20:18 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/parser/Parser.java
> +        final var lexer = new Java9Lexer(CharStreams.fromString(file.getContent()));
Каких то ресурсоёмких операций в конструкторах при беглом просмотре не обнаружил. А какие предложения? Склеивать файлы в одну последовательность, которую скармливать `accula.api.detector.parserParser`?

2020-07-22 20:26 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Parser.java
> +        final var lexer = new Java9Lexer(CharStreams.fromString(file.getContent()));
Чисто поинтересовался, нужно ли каждый раз заново создавать. Или возможно, api позволяет этого не делать. Вдруг классы являются потокобезопасными. Или вдруг внутри используется много ресурсов. Ожидал получить от автора кода ответы на вопросы такого плана

2020-07-22 20:44 UTC, MarkMarkyMarkus commented on api/src/main/java/org/accula/api/detector/parser/Parser.java
> +        final var lexer = new Java9Lexer(CharStreams.fromString(file.getContent()));
Это надо потестировать. Пока не могу сказать точно.

2020-07-23 00:07 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        Token begin = (Token) edge.getSequence().get(sequenceEndIndex - cloneLength);
Нет. `cloneLength` это длина от `Node` конкретного `TreeCLoneClass` до `root`. А `edge` - ребро, выходящее из упомянутого `Node`. `edge` хранит в себе весь sequence целиком, с указателями на конкретный промежуток, которому он соответсвует, так что `getBegin()` возвращает позицию символа (токена), который идёт после `Node`.

2020-07-23 00:11 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        int sequenceEndIndex = edge.getBegin();
Есть такое :) Было желание назвать переменную `hahActuallyEnd`. `getBegin()` возвращает позицию (индекс в `sequence`) токена для ребра, исходящего из `Node`. А нас интересует часть `sequence'а` которая до `Node`, поэтому значение, возвращаемое `getBegin()` соответствует концу интересующего нас отрезка `sequence'а`

2020-07-23 00:13 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        int sequenceEndIndex = edge.getBegin();
Без поллитра не разобраться, в общем

2020-07-23 00:16 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void getClonesForCloneClassIntoList(@NonNull final CodeSnippet codeSnippetTarget,
Распараллелить логику в вызывающем методе (`addClonesToListForTargetMethod`). В общем я предлагаю пока оставить так, потому что есть мысли как зарефакторить указанное место в рамках рефакторинга логики метода `addClonesToListForTargetMethod`

2020-07-23 00:18 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void getClonesForCloneClassIntoList(@NonNull final CodeSnippet codeSnippetTarget,
ок

2020-07-23 00:27 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        final var element = edge.getSequence().get(lastElementIndex);
Добавлю проверку, но вообще это конечно TODO для парсера, не надо пустые последовательности класть в дерево

2020-07-23 00:28 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        return (element instanceof EndToken endToken) && (endToken.getIdSequence() == methodId);
:( Ацтой

2020-07-23 00:47 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/parser/Token.java
> +        return Objects.hash(type);
Хэш функция обусловлена требованием для элементов, которые кладём в дерево. То есть **ТОЛЬКО** то, по чему мы делаем `compare` учитывается в `equals` ну и соответственно в хэш-функции.

2020-07-23 00:48 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/parser/Token.java
> +        return type.equals(token.type);
см. [`hashcode`](https://github.com/ACCULA/accula/pull/112#discussion_r459161335)

2020-07-23 00:52 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +    public static boolean matchesToMethod(@NonNull final Edge edge, @NonNull final Long methodId) {
Я вроде как даже словарик открывал, и `matches to` вроде бы именно то, что нужно

2020-07-23 09:21 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                   final int cloneLength = treeCloneClass.getLength();
И в итоге не поменял?

2020-07-23 09:31 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Parser.java
> +
теперь 19 строка пустая)

2020-07-23 09:32 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +
осталась

2020-07-23 09:32 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +
новая лишняя пустая строка

2020-07-23 09:39 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void putCodeSnippetIntoCloneClassCodeSnippetsMap(@NonNull final CodeSnippet codeSnippetValue,
* избыточной наглядности )

2020-07-23 11:18 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                .max(Long::compareTo).orElseThrow();
Исправлено

2020-07-23 11:18 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                .orElseThrow();
Исправлено

2020-07-23 11:25 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +                   final int cloneLength = treeCloneClass.getLength();
И всё то ты замечаешь! Забыл :)

2020-07-23 20:34 UTC, lamtev commented on api/build.gradle.kts
> +val cloneDetectorVersion =
?!

2020-07-23 20:34 UTC, lamtev commented on api/build.gradle.kts
> +
лишняя пустая строка

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +    private static void getClonesForCloneClassIntoList(final CodeSnippet codeSnippetTarget,
Вообще, можно согласиться. Мб что-то типа `fillListWith...` ?

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/JavaListener.java
> +    public JavaListener(final CommonTokenStream tokens) {
`@RequiredArgsConstructor`?

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/JavaListener.java
> +    public Set<Token> getTypeArgs() {
`@Getter`?

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/JavaListener.java
> +public final class JavaListener extends Java9BaseListener {
`package-private`?

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/JavaListener.java
> +    public Stream<List<Token>> getFunctions() {
`package-private`?

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Token.java
> +//Temporally unused class, will be used when generification of input data in CloneIndexer is being introduced
If so, let's remove it. All we know that it's a bad practice to leave unused files

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/TokenFilter.java
> +public final class TokenFilter {
`package-private`?

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +
Все еще есть пустая строка

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        } else {
не нужен else. он только увеличивает вложенность, что не способствует улучшения читаемости

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +            return (lastElement instanceof EndToken) && (methodId.equals( ((EndToken) lastElement).getIdSequence() ));
А ведь машина права. В правой части выражения действительно внешние скобки не нужны

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +            return (lastElement instanceof EndToken) && (methodId.equals( ((EndToken) lastElement).getIdSequence() ));
От себя добавлю, что довольно необычно выглядят дополнительные пробелы межу скобок. Если пройтись форматтером, то тоже слетит такое форматирование.
Да, конструкция получилась не самой простой, ну бывает. При этом дополнительные пробелы, имхо, читаемость не улучшают

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/package-info.java
> +import org.springframework.lang.NonNullApi;
no newline at end of file. Codeclimate тоже так считает)

2020-07-23 20:34 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/SuffixTreeCloneDetector.java
> +            log.error("Invalid data from parser! Failed to get last index with: " + e.getMessage());
Не могу понять, почему нам с @vaddya таких приколов не выдавал код климат

2020-07-23 20:38 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Token.java
> +        return Objects.hash(type);
Т.к этот класс не используется, я его спутал с используемым Token от сухинина. И в него всюду только `Java9Lexer.Identifier` устанавливался в качестве `type`. Поэтому меня смутило это

2020-07-23 20:39 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/TokenFilter.java
> +public class TokenFilter {
`package-private` не добавился вроде

2020-07-23 20:40 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +    public static boolean matchesToMethod(@NonNull final Edge edge, @NonNull final Long methodId) {
Хм 13 плюсов - это, конечно, сильно)

2020-07-23 20:42 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +    public static boolean matchesToMethod(@NonNull final Edge edge, @NonNull final Long methodId) {
Приведу пример: matches regex, а не matches to regex. Если считаешь, что так норм, то окей

2020-07-23 20:43 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/parser/Parser.java
> +        final var lexer = new Java9Lexer(CharStreams.fromString(file.getContent()));
пофиг, время покажет)

2020-07-23 20:50 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +            return (lastElement instanceof EndToken) && (methodId.equals( ((EndToken) lastElement).getIdSequence() ));
В левой части, скобки тоже не то чтобы улучшают ситуацию. И код климат их так же считает лишними

2020-07-24 16:14 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +            return (lastElement instanceof EndToken) && (methodId.equals( ((EndToken) lastElement).getIdSequence() ));
Ну вопрос конечно спорный, что лучше, а что хуже читается. Мне тоже не то что бы нравится такое оформление, но вроде как есть такая практика - явно выделять скобками логические блоки if-statement'а. В сорцах Hibernate к примеру все скобки "пробелятся" (от слова "пробел"). IDE ещё и любезно подсвечивает пары скобок, так что и читается вроде проще с ними, нежели без. Но раз машина (СС) с человеком во главе считают что лучше убрать - могу убрать. Или можно третье мнение послушать - @vaddya?

2020-07-24 16:15 UTC, VanyaKrylov commented on api/build.gradle.kts
> +val cloneDetectorVersion =
Затру (сотру) форс пушем :)

2020-07-24 16:16 UTC, vaddya commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +            return (lastElement instanceof EndToken) && (methodId.equals( ((EndToken) lastElement).getIdSequence() ));
Скобки зло, убить

PS
Любитель на скале вызывать методы как
`object method arg`

2020-07-24 16:32 UTC, VanyaKrylov commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        } else {
А у меня после объявления класса (строка 14) нет пустой строки... :/

2020-07-24 19:16 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +        } else {
Там просто появилась новая рядом. И git diff merge посчитал будто это все та же старая пустая строка. ок

2020-07-24 19:29 UTC, lamtev commented on api/src/main/java/org/accula/api/detector/util/SuffixTreeUtils.java
> +            return (lastElement instanceof EndToken) && (methodId.equals( ((EndToken) lastElement).getIdSequence() ));
> В сорцах Hibernate 
Ты еще сорцы lucene не читал =) Да, @vaddya ?

2020-07-24 19:34 UTC, lamtev approved these changes
Squash and merge

2020-07-24 19:35 UTC, vaddya approved these changes

2020-07-24 20:41 UTC, merged