Wrapper over git cli for code loading (#111)
ACCULA/accula pull request #117
Opened 2020-08-01 18:00 UTC by lamtev

Closes #111

2020-08-03 18:05 UTC, vaddya requested changes

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                .supplyAsync(safe(subdirectory).writing(() -> {
может writing/reading сразу будут возвращать CompletableFuture?

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                currentFile.add(line);
Идея ругается, говорит NPE мб

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/git/Git.java
> +            case 7: {
Коммент бы, когда 6, когда 7

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/git/Git.java
> +        try (final var stdoutLines = new BufferedReader(new InputStreamReader(process.getErrorStream(), UTF_8)).lines()) {
Мне казалось, что try-with-resources неявно final, раньше даже Идея ругалась мол нафига его final помечать кажется

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +        this.git = new Git(root, Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 10));
Кажется это нарушение инверсии зависимости. Git должен быть бином и инжектится в GitCodeLoader. И не уверен, что надо так много тредов..

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                                        .map(file -> new FileEntity(snapshot, file.getName(), filesContent.get(file))))))
https://twilio-cms-prod.s3.amazonaws.com/original_images/Screen-Shot-2017-03-06-at-5.11.06-PM.png

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                        return usingStdoutLines(process, Collections.emptyMap(), lines -> {
Параметр фолбек может намекает, что лучше Option заюзать и на нем потом вызвать orElse

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                            return ret == SUCCESS ? this : remoteAlreadyExists.test(process) ? this : null;
Не, надо или скобочки ставить, или разнести, не читаемо

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(files -> {
Мне кажется если это вынести в метод, то и читать легче будет, и чейн не придется в одну строчку писать

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +        final var repoGitDirectory = Path.of(snapshot.getRepo().getOwner().getLogin() + "_" + snapshot.getRepo().getName());
snapshot.getRepo() 3 раза за 2 строчки вызывается, я б вынес в переменную, читать удобнее будет

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                                Lambda::firstArg
Сходу не понятно, когда коллизии могут быть, и почему именно first

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +            Mono<Stream<org.accula.api.code.DiffEntry>>
А нафиг тут fully qualified?

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(diffEntry -> {
Может тоже бы вынес в отдельный метод, чтобы не городить такие отступы. И понятнее что происходит

2020-08-03 18:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                currentFile = new StringJoiner(System.lineSeparator());
Не понял, почему не инициализировать сразу при объявлении переменной

2020-08-03 18:08 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +            Mono<Stream<org.accula.api.code.DiffEntry>>
Чтобы читающим код было видно, из какого пакета взят класс =)
А если серьезно, то есть коллизия

2020-08-03 18:09 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +            Mono<Stream<org.accula.api.code.DiffEntry>>
Строкой ниже кажется тот же класс, не? И нет коллизии

2020-08-03 18:10 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +            Mono<Stream<org.accula.api.code.DiffEntry>>
А, назови просто тот, который в пакете Git -> GitDiffEntry

2020-08-03 18:23 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                                Lambda::firstArg
какие коллизии?

2020-08-03 18:24 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                                Lambda::firstArg
Я может не понимаю, зачем тут комбайнер

2020-08-03 18:28 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                                Lambda::firstArg
Чтобы результат был не `Tuple2<Repo, Repo>`, а просто `Repo`

2020-08-03 18:29 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                                Lambda::firstArg
Возможно я просто не юзал так, но если бы после zip был просто map, берущий первый аргумент, мне было бы понятнее

2020-08-03 18:30 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +            Mono<Stream<org.accula.api.code.DiffEntry>>
Блин, получится, что 1 класс с префиксом, а другие нет 😔

2020-08-03 18:32 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +            Mono<Stream<org.accula.api.code.DiffEntry>>
Зато понятно, что где

2020-08-03 18:33 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +            Mono<Stream<org.accula.api.code.DiffEntry>>
Когда видишь класс в коде -- ты сходу не видишь откуда он импортирован. Мне кажется хороший тон -- именовать классы более менее уникальным образом. Тот же git.File я бы тоже назвал более специфично

2020-08-03 18:38 UTC, lamtev commented on api/src/main/java/org/accula/api/code/git/Git.java
> +            case 7: {
Думал в целом понятно из контекста с учетом формата строки в комментарии к методу.
Типа если переименование, то есть base_filename и head_filename. В других случаях есть достаточно 1 названия. Могу что-то такое в код добавить

2020-08-03 18:40 UTC, lamtev commented on api/src/main/java/org/accula/api/code/git/Git.java
> +        try (final var stdoutLines = new BufferedReader(new InputStreamReader(process.getErrorStream(), UTF_8)).lines()) {
Согласен, тут это лишний шум. Исправлю. И в методе выше

2020-08-03 18:50 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +        this.git = new Git(root, Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 10));
Inversion of control разве об этом? `Git` - более нигде неиспользуемый класс. Предоставляет функциональность, необходимую `GitCodeLoader`

2020-08-03 18:52 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(files -> {
Плюсую

2020-08-03 18:52 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +        final var repoGitDirectory = Path.of(snapshot.getRepo().getOwner().getLogin() + "_" + snapshot.getRepo().getName());
Согласен

2020-08-03 18:53 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +        this.git = new Git(root, Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 10));
С одной стороны да, с другой стороны много где так, что класс используется в одном другом классе, и все равно становится бином..

2020-08-03 18:54 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +            Mono<Stream<org.accula.api.code.DiffEntry>>
Эмм. У нас тут джава, а не си, чтобы префиксами обмазываться =)

2020-08-03 18:55 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +        this.git = new Git(root, Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 10));
Мне кажется Git можно рассматривать не как часть имплементации GitCodeLoader, а как внешнюю зависимость для него, которая предоставляет интерфейс взаимодействия с утилитой

2020-08-03 19:02 UTC, lamtev commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                currentFile.add(line);
В теории может быть. Но на практике ни в тестах, ни при запуске приложения такого еще не было. Поймаем npe - значит есть баг в этом алгоритме, буду фиксить

2020-08-03 19:04 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +        this.git = new Git(root, Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 10));
Мб еще интерфейс надо сделать?) Чтобы можно было гибко менять реализацию =)

2020-08-03 19:05 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +        this.git = new Git(root, Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 10));
Вообще было бы неплохо, без шуток. Это же рил абстракция для GitCodeLoader, которую ему можно замокать в тестах, например

2020-08-03 19:06 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                                Lambda::firstArg
Эта фигня `Lambda::firstArg` - вполне экспериментальная вещь. Если не читается, то заменю на `(repo1, repo2) -> repo1`. Думаю, `map` будет явно лишним, ведь именно комбинатор для этой цели существует в `zip`

2020-08-03 19:07 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                                Lambda::firstArg
Да, согласен, скорее всего просто не встречался

2020-08-03 19:12 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +        this.git = new Git(root, Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 10));
Mockito умеет даже финальные классы мокать, так что не буду интерфейс тут еще делать

2020-08-03 19:13 UTC, lamtev commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                        return usingStdoutLines(process, Collections.emptyMap(), lines -> {
Надо подумать. Кажется неплохой идеей

2020-08-03 19:21 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(diffEntry -> {
Что именно тут вынести? И так вроде вынесено) В методе только паттерн матчинг

2020-08-03 19:23 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(diffEntry -> {
Его и вынести
FileEntity toFileEntity(DiffEntry diffEntry)

2020-08-03 19:23 UTC, lamtev commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                currentFile = new StringJoiner(System.lineSeparator());
В цикле происходит перезапись все равно. Логика такая, что по мере необходимости во время итерирования по строкам создается эта шутка.
Код не очень понятный. Если есть идеи, как улучшить - Welcome)

2020-08-03 19:27 UTC, vaddya commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                    fromLine = Integer.MIN_VALUE;
Скорее 0)

2020-08-03 19:27 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(diffEntry -> {
И тогда этот метод будет зачем нужен, только чтобы вызвать другой?

2020-08-03 19:29 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(diffEntry -> {
Стримами обмазать. Но как хочешь, можно оставить

2020-08-03 19:29 UTC, lamtev commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                    fromLine = Integer.MIN_VALUE;
Для нуля нет симметричной константы) Годится все, что меньше 1

2020-08-03 19:30 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(diffEntry -> {
Маленькие функции просто, проще читать, тестировать. Четко понятно, что метод берет один DiffEntry и парсит один FileEntity

2020-08-03 19:31 UTC, vaddya commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                    fromLine = Integer.MIN_VALUE;
Да, понимаю, просто отрицательный номер строки... Ну, пусть

2020-08-03 19:31 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(diffEntry -> {
Убедил

2020-08-03 19:43 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(diffEntry -> {
Не убдил. Получается метод с 4 параметрами =(

2020-08-03 19:43 UTC, vaddya commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(diffEntry -> {
Ок, откатывай

2020-08-03 20:07 UTC, lamtev commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                .supplyAsync(safe(subdirectory).writing(() -> {
сделал

2020-08-03 20:07 UTC, lamtev commented on api/src/main/java/org/accula/api/code/git/Git.java
> +        try (final var stdoutLines = new BufferedReader(new InputStreamReader(process.getErrorStream(), UTF_8)).lines()) {
сделал

2020-08-03 20:07 UTC, lamtev commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                        return usingStdoutLines(process, Collections.emptyMap(), lines -> {
сделал

2020-08-03 20:07 UTC, lamtev commented on api/src/main/java/org/accula/api/code/git/Git.java
> +                            return ret == SUCCESS ? this : remoteAlreadyExists.test(process) ? this : null;
готово

2020-08-03 20:07 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                        .map(files -> {
вынес

2020-08-03 20:07 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +        final var repoGitDirectory = Path.of(snapshot.getRepo().getOwner().getLogin() + "_" + snapshot.getRepo().getName());
вынес

2020-08-03 20:08 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +                                Lambda::firstArg
заменил на явную лямбду

2020-08-03 20:08 UTC, lamtev commented on api/src/main/java/org/accula/api/code/GitCodeLoader.java
> +            Mono<Stream<org.accula.api.code.DiffEntry>>
Да здравствует язык Си!

2020-08-03 20:25 UTC, vaddya submitted a review, later dismissed

2020-08-03 20:31 UTC, vaddya submitted a review, later dismissed

2020-08-04 11:23 UTC, vaddya approved these changes

2020-08-04 11:37 UTC, merged