Configuration props for projects
ACCULA/accula pull request #132
Opened 2020-09-26 18:22 UTC by vaddya

2020-09-27 13:28 UTC, lamtev requested changes
Обсудили что доделать

2020-10-10 10:12 UTC, lamtev commented on api/src/main/java/org/accula/api/config/WebSecurityConfig.java
> +                        .pathMatchers(GET, "/api/projects/{id}/headFiles").permitAll()
а зачем всем?)

2020-10-10 10:14 UTC, vaddya commented on api/src/main/java/org/accula/api/config/WebSecurityConfig.java
> +                        .pathMatchers(GET, "/api/projects/{id}/headFiles").permitAll()
Дебажил кажется, пофиксил

2020-10-10 10:33 UTC, lamtev commented on api/src/main/java/org/accula/api/db/model/Project.java
> +                .fileMinSimilarityIndex(0)
== вообще не искать переименования

2020-10-10 10:34 UTC, lamtev commented on api/src/main/resources/db/migration/V1__create.sql
> +    excluded_files            TEXT[],
может быть NULL ?

2020-10-10 10:46 UTC, vaddya commented on api/src/main/java/org/accula/api/db/model/Project.java
> +                .fileMinSimilarityIndex(0)
А какое значение лучше? 1?

2020-10-10 10:47 UTC, vaddya commented on api/src/main/resources/db/migration/V1__create.sql
> +    excluded_files            TEXT[],
А это точно лучше, чем пустой массив?

2020-10-10 10:47 UTC, vaddya commented on api/src/main/resources/db/migration/V1__create.sql
> +    excluded_files            TEXT[],
А, ты наоброт имеешь ввиду добавить NOT NULL
Точно, спасибо

2020-10-10 10:47 UTC, lamtev commented on api/src/main/java/org/accula/api/db/model/Project.java
> +                .fileMinSimilarityIndex(0)
1 - наверное слишком жестко. Мб 3-5?

2020-10-10 10:48 UTC, vaddya commented on api/src/main/java/org/accula/api/db/model/Project.java
> +                .fileMinSimilarityIndex(0)
Поставлю 5.

2020-10-10 10:48 UTC, lamtev commented on api/src/main/resources/db/migration/V1__create.sql
> +    excluded_files            TEXT[],
и я про это: сейчас может быть нулл

2020-10-10 10:51 UTC, lamtev approved these changes

2020-10-10 10:53 UTC, merged