dg/#9-pull-requests-parser
ACCULA/accula pull request #31
Opened 2020-04-15 22:00 UTC by dariaGap

2020-05-11 20:24 UTC, vaddya requested changes

2020-05-11 20:24 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> + {
В Java принят code style, по которому `{` остается на той же строке, что и аргументы функции. Если ты пользуешься IDEA, попробуй нажать Ctrl+Alt+L, а то в файле очень много кода не по код стайлу. Если пользуешься не идеей, то придется это делать как то руками

2020-05-11 20:24 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +        if (pr.getUser().getName().isEmpty()) {
`getName()` может вернуть null и `isEmpty()` упадет с NullPointerException

2020-05-11 20:24 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            userName = pr.getUser().getName();
А зачем вообще name нужен? В гитхабе нейм это просто строка длиной до 255 символов, никак не идентифицирующая пользователя в отличии от логина

2020-05-11 20:24 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
Не очень понимаю зачем снова делается запрос за юзером, если строкой выше уже вызывается метод `getUser()`

2020-05-11 20:24 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +        final ArrayList<String> excludeFiles = new ArrayList<>();
В Java принято при объявлении переменной указывать наиболее общий тип интерфейса -- в данном случае `List<String> excludeFiles`

2020-05-11 20:24 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +        pullRequestInfo.subscribe(pr -> {
Я не эксперт в реакторе, но кажется здесь что-то не то. Код в обработчике должен выстраиваться в цепочку вызовов функций, а этот вызов __блокирующий__. За помощью вызывается @lamtev

2020-05-11 20:24 UTC, vaddya commented on api/src/main/java/org/accula/api/model/GitPullRequest.java
> +    public GitPullRequest(){
С точки зрения Java этот конструктор абсолютно бесполезный, о чем и говорит код клаймет. Вызывать `super()` нужно только если ты наследуешься от другого класса, и то не всегда

2020-05-11 20:24 UTC, vaddya commented on api/src/main/java/org/accula/api/model/WebHookModel.java
> +    private GitPullRequest pull_request;
Тоже верное замечание, переменные в Java принято называть в формате CamelCase, а не snake_case.

2020-05-11 20:24 UTC, vaddya commented on api/src/main/java/org/accula/api/routers/StatusRouter.java
> +import org.springframework.web.reactive.function.server.ServerResponse;
Ненужная перестановка

2020-05-11 20:24 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +        final String[] splitedUrl = pr.getUrl()
Выглядит очень хрупко... Или костыльно...

2020-05-11 20:24 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +     final String prRef = prNumber > 0 ? "refs/pull/"+ prNumber+ "/head":"refs/pull/*/head";
Не очевидно, что за манипуляции при `prNumber < 1`

2020-05-11 20:24 UTC, vaddya commented on api/build.gradle.kts
> +    implementation("org.eclipse.jgit:org.eclipse.jgit:4.6.0.201612231935-r")
А почему такой древний клиент? 2016 года судя по названию. Есть версии > 5
https://mvnrepository.com/artifact/org.eclipse.jgit/org.eclipse.jgit

2020-05-11 22:43 UTC, MarkMarkyMarkus requested changes

2020-05-11 22:43 UTC, MarkMarkyMarkus commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +        return ok().build();
Мне кажется лучше запустить задачу сбора данных в другом треде, а ответ вернуть сразу, не дожидаясь загрузки файлов и поиска клонов. Также лучше вынести логику, не относящуюся к обработке запроса, в другой класс.

2020-05-11 22:43 UTC, MarkMarkyMarkus commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +        excludeFiles.add("StartStopTest.java");
Например:
```java 
final var excludeFiles = Set.of("TestBase.java", "StartStopTest.java");
```

2020-05-13 07:09 UTC, dariaGap commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +     final String prRef = prNumber > 0 ? "refs/pull/"+ prNumber+ "/head":"refs/pull/*/head";
Метод позволяет вытянуть файлы из всех pull request или из одного конкретного. Для вытягивания всех pr используется номер пула 0. Я добавлю комментарии в код.

2020-05-13 07:11 UTC, dariaGap commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            userName = pr.getUser().getName();
jgit позволяет получить информацию об авторе в виде имени и электронной почты. Если имя не заполнено, тогда используется логин.

2020-05-13 07:12 UTC, dariaGap commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
имя пользователя не выдается в информации от хука. Нужен дополнительный запрос, чтобы его получить.

2020-05-13 07:14 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            userName = pr.getUser().getName();
Логин по ощущениям должен использовать всегда

2020-05-13 07:14 UTC, dariaGap commented on api/src/main/java/org/accula/api/routers/StatusRouter.java
> +import org.springframework.web.reactive.function.server.ServerResponse;
Была сделана давно, поскольку на это ругался code climate

2020-05-13 07:16 UTC, vaddya commented on api/src/main/java/org/accula/api/routers/StatusRouter.java
> +import org.springframework.web.reactive.function.server.ServerResponse;
Нужно откатить

2020-05-14 19:09 UTC, dariaGap commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            userName = pr.getUser().getName();
Перепроверила еще раз. Не нашла, где можно получать логин. Подозреваю, что это связано с тем, что git в приоритет ставит именно имя автора.

2020-05-14 19:12 UTC, dariaGap commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +        return ok().build();
А разве сейчас не так? Mono, вроде бы, асинхронный. По крайней мере, я в выводе debug вижу, что ответ возвращается раньше, чем запускается git. Логику вынесла в класс Files.

2020-05-14 22:37 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            userName = pr.getUser().getName();
А `pr.getUser().getLogin()` разве не логин возвращает?

2020-05-14 22:41 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
А зачем нам нужно имя пользователя? Недостаточно только логина?

2020-05-15 10:14 UTC, dariaGap commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
Имя пользователя нужно для клонированных репозиториев. Там нет возможности идентифицировать автора по логину, используется name. Я использую имя автора, чтобы не включать в выборку файлы из репозиториев, созданные этим же студентом. Иначе может получится, что он сам у себя списал.

2020-05-15 10:16 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
Еще раз повторяю, имя это просто строка, которую можно менять через настройки. Везде нужно использовать логин!

Вот пример запроса "по мне", видно, что имя это просто строка, которую я могу в любой момент поменять через настройки.
https://api.github.com/users/vaddya

2020-05-15 10:20 UTC, lamtev commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
`+`, путь к репо ПОЛЬЗОВАТЕЛЯ (не организации) для клонирования: `github.com/login/repo.git`

2020-05-15 10:31 UTC, dariaGap commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
Я клонирую репозитории со старыми (и текущим) проектами. Потом из них достаю pull request-ы. Глупо было бы клонировать репозитории каждого студента. Из клонированного репозитория технополиса об авторе пула я могу узнать только имя. Не логин. Это просто не предусмотрено библиотекой. Может путь с клонированием репозитория конкретного пользователя и подошел бы для получения файлов нового pr, но нам же нужно его еще с чем-то сравнивать. То есть, все равно нужен список всех pr в репозитории проекта.

2020-05-15 10:35 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
А `studentPR.getPullRequest().getUser().getLogin()` ?

2020-05-15 10:42 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
Ладно, это ограничения JGit, он не привязан к гитхабу
Ну если это работает, то пусть, но есть ощущение, что не сработает

2020-05-15 10:49 UTC, dariaGap commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
Это информация о новом pr от github. Стартовая точка. Здесь логин доступен, да. На основе информации, что этим пользователем был сделан pr вытягиваются его файлы через клонирование, и файлы, с которыми мы это будем сравнивать. При получении файлов через клонирование мы не можем сказать, какой логин у автора файла. Таким образом, мы знаем только логин студента, в чьих файлах мы ищем клонов. Но не знаем логинов авторов других файлов, у которых наш студент заимствовал свой код. Так как данный pr может быть не первым pr этого студента в репозитории, нужно отсеять его файлы из выборки для сравнения, для этого я использую имя студента, так как, напоминаю, на данном этапе логин уже не доступен. Альтернативой имени автора в данном случае может служить только его почта. Имя и почта - единственные данные об авторе файла, которые я могу получить, вытягивая pr из склонированных репозиториев.

2020-05-15 10:52 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
А зачем мы смотрим на коммиты, если можно просто отсечь предыдущие пулл риквесты этого автора?

2020-05-15 10:54 UTC, vaddya commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
Коммиты просто ненадежная вещь, вот пример

https://github.com/vaddya/automated-testing/commits/master

тут автор всех коммитов, кроме первого, некий vaddya, и это имя можно указывать у себя локально какое хочешь. У первого же коммита есть автор с ссылкой на гитхаб репозитрий.

2020-05-15 11:27 UTC, dariaGap commented on api/src/main/java/org/accula/api/handlers/DataParserHandler.java
> +            return WebClient.create(userUrl)
Я еще посмотрю, можно ли с этим что-то сделать, но уже не на этой неделе.

2020-05-27 17:58 UTC, vaddya commented
Надо поправить кодклаймет
И можно в двух предложениях написать, о чем пулл риквест, я уже забыл

2020-05-27 19:00 UTC, dariaGap commented
> И можно в двух предложениях написать, о чем пулл риквест, я уже забыл
По приходу хука получаем список измененных файлов в новом pr и файлы, с которыми будем этот pr сравнивать. Files.getPRFiles() реализует получение файлов конкретного pr, так что это можно будет использовать для фронта.

2020-05-27 19:01 UTC, vaddya commented
> > И можно в двух предложениях написать, о чем пулл риквест, я уже забыл
> 
> По приходу хука получаем список измененных файлов в новом pr и файлы, с которыми будем этот pr сравнивать. Files.getPRFiles() реализует получение файлов конкретного pr, так что это можно будет использовать для фронта.

Уже реализовано в рамках #62, но посмотрим, может можно заимствовать какие то части кода туда.

2020-05-30 00:03 UTC, lamtev commented
Resolved in #56 and #60

2020-05-30 00:03 UTC, closed without merging